<?php

function formation_prestashop_menu(){
  $items['prest/test/toto'] = array(
    'title' => 'Ma première page',
    'description' => 'Une page de demo',
    'page callback' => 'formation_page_demo',
    'access arguments' => array('formation demo'),
  );
  return $items;
}

function formation_page_demo(){
   return 'Salut toto';
}

function formation_prestashop_permission() {
  return(array(
    'formation demo' => array(
      'title' => t('Accéder aux démos'),
      'description' => t('Permissions d acceder démo')
    )
  ));
}

function formation_prestashop_menu_alter(&$items){
  $items['admin/modules'] = array(
    'title' => 'Liste des modules',
    'access callback' => TRUE,
  );
  return $items;
}

function formation_prestashop_preprocess_node(&$vars){
  if($vars['type'] = 'couleurpage'){
    $term_taxo = $vars['field_taxo_couleur'][0]['taxonomy_term']->name;
    $vars['classes_array'][] = strtolower($term_taxo);
  }
}
